coisa = input('Digite qualquer coisa: ')

print(f'{coisa} é do tipo {type(coisa)}.')
print(f'{coisa} só tem espaços: {coisa.isspace()}.')
print(f'{coisa} só tem números: {coisa.isnumeric()}.')
print(f'{coisa} é alfabetico: {coisa.isalpha()}.')
print(f'{coisa} é alfabetico: {coisa.isalnum()}.')
print(f'{coisa} só tem letras maiusculas: {coisa.isupper()}.')
print(f'{coisa} só tem letras minusculas: {coisa.islower()}.')
print(f'{coisa} está capitalizado: {coisa.istitle()}.')
