num = int(input('Insira o numero do qual deseja saber a tabuada: '))

print('-' * 15)
print('{:2} X {} = {}'.format(1, num, num*1))
print('{:2} X {} = {}'.format(2, num, num*2))
print('{:2} X {} = {}'.format(3, num, num*3))
print('{:2} X {} = {}'.format(4, num, num*4))
print('{:2} X {} = {}'.format(5, num, num*5))
print('{:2} X {} = {}'.format(6, num, num*6))
print('{:2} X {} = {}'.format(7, num, num*7))
print('{:2} X {} = {}'.format(8, num, num*8))
print('{:2} X {} = {}'.format(9, num, num*9))
print('{:2} X {} = {}'.format(10, num, num*10))
print('-' * 15)
